runtime: java17
env: flex

env_variables:
  SPRING_PROFILES_ACTIVE: prod  # Optional: set to 'prod' for production profile

entrypoint: java -jar target/your-app.jar

instance_class: F2  # Choose the instance type based on your needs (F2 is a basic instance)
